---
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: {{ .Values.dsName }}
  labels:
    app: {{ .Values.appName }}
spec:
  name: {{ .Values.dsName }}.yaml
  datasources:
    - name: InfluxDB
      type: influxdb
      access: proxy
      database: {{ .Values.global.db.dbName }}
      user: {{ .Values.global.db.readUser }}
      url: {{ .Values.global.db.url }}
      jsonData:
        httpMode: GET
      secureJsonData:
        password: {{ .Values.global.db.readUserPassword }}
