---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-influxdb-{{ .Release.Name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5G
  volumeMode: Filesystem
