---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appName }}
  name: influxdb-{{ .Release.Name }}
spec:
  ports:
  - name: {{ .Values.service.portName|quote }}
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.appName }}
  type: ClusterIP
