grafana:
  appName: grafana
  dsName: dht22
  dashboardName: babyroom-current
  adminUser: admin
  adminPassword: ${CONSOLE_PASS}
  service:
    port: 3000
  ingress:
    host: ${GRAFANA_URL}

influxdb:
  appName: influxdb
  image:
    repository: docker.io/library/influxdb:latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8086
    portName: 8086-tcp
  
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ingress:
    host: ${INFLUX_URL}
  
global:
  db:
    dbName: temperature
    adminUser: admin
    adminUserPassword: ${DB_ADMIN_PASS}
    readUser: grafana
    readUserPassword: ${DB_PASS}
    writeUser: pi
    writeUserPassword: ${DB_PASS}
    url: http://influxdb:8086
