appName: influxdb
image:
  repository: docker.io/library/influxdb:latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8086
  portName: 8086-tcp

podSecurityContext: {}
securityContext: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

ingress:
  host: <url>

global:
  db:
    dbName: temperature
    adminUser: admin
    adminUserPassword: password
    readUser: grafana
    readUserPassword: password
    writeUser: pi
    writeUserPassword: password
    url: http://influxdb:8086
